
export const SERVER_ERROR = "SERVER_ERROR";

export const USER_SIGNED_IN = "USER_SIGNED_IN";
export const USER_SIGN_IN_FAILED = "USER_SIGN_IN_FAILED";
export const USER_SIGNED_UP = "USER_SIGNED_UP";
export const USER_SIGN_UP_FAILED = "USER_SIGN_UP_FAILED";
export const USER_SIGNED_OUT = "USER_SIGNED_OUT";

export const GAME_LOADED = "GAME_LOADED";
export const GAME_LOAD_FAILED = "GAME_LOAD_FAILED";
export const GAME_PAGE_LOADED = "GAME_PAGE_LOADED";
export const GAME_PAGE_LOAD_FAILED = "GAME_PAGE_LOAD_FAILED";
export const GAME_DOWNLOADED = 'GAME_DOWNLOADED';
export const GAME_DOWNLOAD_FAILED = 'GAME_DOWNLOAD_FAILED';
export const REVIEW_ADDED = 'REVIEW_ADDED';
export const REVIEW_ADD_FAILED = 'REVIEW_ADD_FAILED';
export const REVIEW_DELETED = 'REVIEW_DELETED';
export const REVIEW_DELETE_FAILED = 'REVIEW_DELETE_FAILED';
export const RATING_LOADED = 'RATING_LOADED';
export const RATING_LOAD_FAILED = 'RATING_LOAD_FAILED';